# Generated by Django 5.2.3 on 2025-06-30 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='carrinho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.carrinho'),
            preserve_default=False,
        ),
    ]
