# Generated by Django 5.2.3 on 2025-06-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_itempedido_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='carrinho',
        ),
    ]
