# Generated by Django 5.2.3 on 2025-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_itemcarrinho_carrinho_itens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data_pedido',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco_entrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue')], default='pendente', max_length=20),
        ),
    ]
