# Generated by Django 5.2.3 on 2025-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_rename_data_pedido_pedido_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
